version: '3.8'
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - /mnt/data/cookies.txt:/mnt/data/cookies.txt  # Ensure cookies file is accessible
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
    restart: unless-stopped