version: "3"
services:
  youtube-rtsp:
    build: .
    ports:
      - "80:80"
      - "8554:8554/tcp"  # RTSP over TCP
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY} # Uses API key from Koyeb environment
    restart: always
    volumes:
      - ./logs:/var/log/apache2